### ISSUE TITLE
SEGV when encoding %Config

### ISSUE THREAD

**Issue by atoomic** [FGasper/p5-CBOR-Free#6]
```perl
#!perl

use strict;
use warnings;

use Config;

use CBOR::Free ();

CBOR::Free::encode(\%Config);
print qq[ok\n];
```

using gdb we can see where the errors comes from
```
Program received signal SIGSEGV, Segmentation fault.

0x00007fffefd66ac7 in _encode (value=0x0, encode_state=0x7fffffffda80) at cbor_free_encode.c:197
197	    if (!SvROK(value)) {
(gdb) bt
#0  0x00007fffefd66ac7 in _encode (value=0x0, encode_state=0x7fffffffda80) at cbor_free_encode.c:197
#1  0x00007fffefd67cc3 in _encode (value=0x6054f0, encode_state=0x7fffffffda80) at cbor_free_encode.c:397
#2  0x00007fffefd67f54 in cbf_encode (value=0x6054f0, encode_state=0x7fffffffda80, RETVAL=0x605718) at cbor_free_encode.c:459
#3  0x00007fffefd65cdf in XS_CBOR__Free_encode (cv=0x681cb8) at Free.xs:88
#4  0x00007ffff7960599 in Perl_pp_entersub () at pp_hot.c:5237
#5  0x00007ffff794ebbc in Perl_runops_standard () at run.c:41
#6  0x00007ffff7865a19 in S_run_body (oldscope=1) at perl.c:2716
#7  0x00007ffff78654f6 in perl_run (my_perl=0x603010) at perl.c:2639
#8  0x0000000000400e8a in main (argc=2, argv=0x7fffffffdf48, env=0x7fffffffdf60) at perlmain.c:127

Breakpoint 2, _encode (value=0x0, encode_state=0x7fffffffda80) at cbor_free_encode.c:197
197	    if (!SvROK(value)) {

(gdb) p value
$2 = (SV *) 0x0
```

suggestion consider NULL as undef :-)
```diff
diff --git a/cbor_free_encode.c b/cbor_free_encode.c
index 3cc469e..5b1cc71 100644
--- a/cbor_free_encode.c
+++ b/cbor_free_encode.c
@@ -194,6 +194,9 @@ void _encode( pTHX_ SV *value, encode_ctx *encode_state ) {
         _croak_encode( encode_state, NULL );
     }

+    if (value == NULL)
+        value = &PL_sv_undef;
+
     if (!SvROK(value)) {

         if (SvIOK(value)) {
```

**Comment by atoomic** [comment]
we are calling _encodeline 397
```
  >│397                         _encode( aTHX_ HeVAL(h_entry), encode_state );                                         │
```
with
```
(gdb) p	*h_entry
$2 = {
  hent_next = 0x0,
  hent_hek = 0x64b5a0,
  he_valu = {
    hent_val = 0x0,
    hent_refcount = 0
  }
}
(gdb) p *( h_entry.hent_hek )
$5 = {
  hek_hash = 0,
  hek_len = -2,
  hek_key =     "("
}
```

**Comment by FGasper** [comment]
@atoomic Good to close this?

**Comment by atoomic** [comment]
yeap let's close it, the most important was to get the unit test so we detect such a regression in he future
all good!
